DROP DATABASE IF EXISTS Proyecto_libre; 
CREATE DATABASE IF NOT EXISTS Proyecto_libre; 
USE Proyecto_libre; 



CREATE TABLE jugador (
    id          INT PRIMARY KEY,
    nombre      VARCHAR(50),
    apellido    VARCHAR(50),
    posicion    VARCHAR(10) CHECK (posicion IN ('portero', 'defensa', 'medio', 'delantero')),
    pierna_habil CHAR(1)   CHECK (pierna_habil IN ('D', 'Z', 'A'))
);

-- INSERT jugadores LaLiga EA Sports 2025-2026
-- Posiciones: 'portero', 'defensa', 'medio', 'delantero'
-- Pierna hábil: 'D' (derecha), 'Z' (zurda), 'A' (ambas)

INSERT INTO jugador (id, nombre, apellido, posicion, pierna_habil) VALUES

-- REAL MADRID
(1,  'Thibaut',    'Courtois',      'portero',   'Z'),
(2,	 'Andrey',	   'Lunin',			'portero',	 'D'),
(3,  'Dani',       'Carvajal',      'defensa',   'D'),
(4,  'Trent',      'Arnold',      	'defensa',   'D'),
(5,  'Alvaro',     'Carreras',      'defensa',   'Z'),
(6,  'Fran',       'Garcia',      	'defensa',   'Z'),
(7,  'Ferland',    'Mendy',         'defensa',   'Z'),
(8,  'Eder',       'Militao',       'defensa',   'D'),
(9,  'Antonio',    'Rudiger',       'defensa',   'D'),
(10, 'Dean',       'Huijsen',      	'defensa',   'D'),
(11, 'David',      'Alaba',      	'defensa',   'Z'),
(12, 'Raul',       'Asencio',       'defensa',   'D'),
(13, 'Jude',       'Bellingham',    'medio',     'D'),
(14, 'Fede',       'Valverde',      'medio',     'D'),
(15, 'Eduardo',    'Camavinga',     'medio',     'Z'),
(16, 'Aurelien',   'Tchuameni',     'medio',     'D'),
(17, 'Arda',       'Güler',         'medio',     'Z'),
(18, 'Dani',   	   'Ceballos',      'medio',     'D'),
(19, 'Brahim',     'Diaz',          'medio',     'D'),
(20, 'Franco',     'Mastantuono',   'medio',     'Z'),
(21, 'Vinicius',   'Junior',        'delantero', 'D'),
(22, 'Kylian',     'Mbappe',        'delantero', 'D'),
(23, 'Rodrygo',    'Goes',          'delantero', 'D'),
(24, 'Gonzalo',    'Garcia',        'delantero', 'D'),
(25, 'Daniel',     'Yañez',         'delantero', 'D'),


-- FC BARCELONA
(26, 'Joan',       'Garcia',        'portero',   'D'),
(27, 'Wojciech',   'Szczensky',     'portero',   'D'),
(28, 'Jules',      'Kounde',        'defensa',   'D'),
(29, 'Ronald',     'Araujo',        'defensa',   'D'),
(30, 'Pau',        'Cubarsi',       'defensa',   'D'),
(31, 'Alejandro',  'Balde',         'defensa',   'Z'),
(32, 'Joao',       'Cancelo',       'defensa',   'D'),
(33, 'Eric',       'Garcia',        'defensa',   'Z'),
(34, 'Gerard',     'Martin',        'defensa',   'Z'),
(35, 'Andreas',    'Christensen',   'defensa',   'D'),
(36, 'Pedri',      'Gonzalez',      'medio',     'D'),
(37, 'Frenkie',    'De Jong',       'medio',     'D'),
(38, 'Marc',       'Casado',        'medio',     'D'),
(39, 'Pablo',      'Gavi',          'medio',     'D'),
(40, 'Fermin',     'Lopez',         'medio',     'D'),
(41, 'Dani',       'Olmo',          'medio',     'D'),
(42, 'Marc',       'Bernal',        'medio',     'Z'),
(43, 'Roony',      'Bardghji',      'medio',     'Z'),
(44, 'Lamine',     'Yamal',         'delantero', 'Z'),
(45, 'Robert',     'Lewandowski',   'delantero', 'D'),
(46, 'Raphinha',   'Belloli',       'delantero', 'Z'),
(47, 'Ferran',     'Torres',        'delantero', 'D'),
(48, 'Marcus',     'Rashford',      'delantero', 'D'),
(49, 'Andres',     'Fernandez',     'delantero', 'D'),
(50, 'Dani',       'Rodriguez',     'delantero', 'D'),

-- ATLETICO DE MADRID
(51, 'Jan',        'Oblak',         'portero',   'D'),
(52, 'Juan',       'Musso',         'portero',   'D'),
(53, 'Jose Maria', 'Gimenez',       'defensa',   'D'),
(54, 'Clement',    'Lenglet',       'defensa',   'D'),
(55, 'Nahuel',     'Molina',        'defensa',   'D'),
(56, 'David',      'Hancko',        'defensa',   'Z'),
(57, 'Robin',      'Le Normand',    'defensa',   'D'),
(58, 'Marc',       'Pubill',        'defensa',   'D'),
(59, 'Reinildo',   'Mandava',       'defensa',   'Z'),
(60, 'Mateo',      'Ruggeri',       'defensa',   'Z'),
(61, 'Rodrigo',    'Mendoza',       'medio',     'D'),
(62, 'Jhonny',     'Cardoso',       'medio',     'D'),
(63, 'Koke',       'Resurreccion',  'medio',     'D'),
(64, 'Pablo',      'Barrios',       'medio',     'D'),
(65, 'Alex',       'Baena',         'medio',     'D'),
(66, 'Thiago',     'Almada',        'medio',     'D'),
(67, 'Marcos',     'Llorente',      'medio',     'D'),
(68, 'Obeb',       'Vargas',        'medio',     'D'),
(69, 'Antoine',    'Griezmann',     'delantero', 'Z'),
(70, 'Julian',     'Alvarez',       'delantero', 'D'),
(71, 'Alexander',  'Sorloth',       'delantero', 'Z'),
(72, 'Ademan',     'Lokman',        'delantero', 'D'),
(73, 'Nico',       'Gonzalez',      'delantero', 'D'),
(74, 'Rayane',     'Belaid',        'delantero', 'D'),
(75, 'Sergio',     'Esteban',       'delantero', 'D'),

-- ATHLETIC CLUB
(76, 'Unai',       'Simon',         'portero',   'D'),
(77, 'Alex',       'Padilla',       'portero',   'D'),
(78, 'Andoni',     'Gorosabel',     'defensa',   'D'),
(79, 'Dani',       'Vivian',        'defensa',   'D'),
(80, 'Aitor',      'Paredes',       'defensa',   'D'),
(81, 'Yeray',      'Alvarez',       'defensa',   'D'),
(82, 'Juan',       'Areso',         'defensa',   'D'),
(83, 'Unai',       'Eguiluz',       'defensa',   'D'),
(84, 'Aymeric',    'Laporte',       'defensa',   'Z'),
(85, 'Iñigo',      'Lekue',         'defensa',   'D'),
(86, 'Yuri',       'Berchiche',     'defensa',   'Z'),
(87, 'Alejandro',  'Rego',          'defensa',   'D'),
(88, 'Mikel',      'Vesga',         'medio',     'D'),
(89, 'Oihan',      'Sancet',        'medio',     'D'),
(90, 'Iñigo',      'deGalarreta',   'medio',     'D'),
(91, 'Mikel',      'Jauregizar',    'medio',     'D'),
(92, 'Adama',      'Boiro',         'medio',     'Z'),
(93, 'Unai',       'Gomez',         'medio',     'Z'),
(94, 'Robert',     'Navarro',       'medio',     'D'),
(95, 'Beñat',      'Prados',        'medio',     'D'),
(96, 'Alez',       'Berenguer',     'delantero', 'D'),
(97, 'Nico',       'Williams',      'delantero', 'D'),
(98, 'Inaki',      'Williams',      'delantero', 'D'),
(99, 'Gorka',      'Guruzeta',      'delantero', 'D'),
(100,'Nico',       'Serrano',       'delantero', 'D'),

-- REAL SOCIEDAD
(101,'Alex',       'Remiro',        'portero',   'D'),
(102,'Unai',       'Marrero',       'portero',   'D'),
(103,'Jon',        'Aramburu',      'defensa',   'D'),
(104,'Igor',       'Zubeldia',      'defensa',   'D'),
(105,'Aritz',      'Elustondo',     'defensa',   'D'),
(106,'Aihen',      'Munoz',         'defensa',   'Z'),
(107,'Sergio',     'Gomez',         'defensa',   'Z'),
(108,'Caleta',     'Car',           'defensa',   'D'),
(109,'Alvaro',     'Odriozola',     'defensa',   'D'),
(110,'Jon',        'Martin',        'defensa',   'D'),
(111,'Jon',        'Gorortxa',      'medio',     'D'),
(112,'Beñat',      'Turrientes',    'medio',     'D'),
(113,'Brais',      'Mendez',        'medio',     'D'),
(114,'Yangel',     'Herrera',       'medio',     'D'),
(115,'Pablo',      'Marin',         'medio',     'D'),
(116,'Arsen',      'Zaakharyan',    'medio',     'D'),
(117,'Take',       'Kubo',          'medio',     'Z'),
(118,'Carlos',     'Soler',         'medio',     'Z'),
(119,'Luka',       'Sucic',         'medio',     'Z'),
(120,'Mikel',      'Oyarzabal',     'delantero', 'Z'),
(121,'Ander',      'Barrenetxea',   'delantero', 'D'),
(122,'Orri',       'Oskarsson',     'delantero', 'Z'),
(123,'Jon',        'Karrikaburu',   'delantero', 'D'),
(124,'Gonzalo',    'Guedes',        'delantero', 'D'),
(125,'Arkaitz',    'Mariezkurrena', 'delantero', 'D'),


-- VILLARREAL
(126,'Diego',      'Conde',         'portero',   'D'),
(127,'Arnau',      'Tenas',         'portero',   'D'),
(128,'Luiz',       'Junior',        'portero',   'D'),
(129,'Alfonso',    'Pedraza',       'defensa',   'Z'),
(130,'Logan',      'Costa',         'defensa',   'D'),
(131,'Alexander',  'Freeman',       'defensa',   'D'),
(132,'Rafa',       'Marin',         'defensa',   'D'),
(133,'Willy',      'Kambwala',      'defensa',   'D'),
(134,'Pau',        'Navarro',       'defensa',   'D'),
(135,'Juan',       'Foyth',         'defensa',   'D'),
(136,'Renato',     'veiga',         'defensa',   'D'),
(137,'Santiago',   'Murillo',       'defensa',   'D'),
(138,'Sergi',      'Cardona',       'defensa',   'D'),
(139,'Dani',       'Parejo',        'medio',     'D'),
(140,'Santi',      'Comesaña',      'medio',     'D'),
(141,'Pape',       'Gueye',         'medio',     'Z'),
(142,'Thomas',     'Partey',        'medio',     'D'),
(143,'Ayoze',      'Perez',         'delantero', 'D'),
(144,'Tani',       'Oluwaseyi',     'delantero', 'D'),
(145,'Alberto',    'Moleiro',       'delantero', 'D'),
(146,'Tajon',      'Buchanan',      'delantero', 'D'),
(147,'Georges',    'Mikautadze',    'delantero', 'D'),
(148,'Gerard',     'Moreno',        'delantero', 'Z'),
(149,'Nicolas',    'Pepe',          'delantero', 'Z'),
(150,'Pau',        'Cabanes',       'delantero', 'D'),

-- REAL BETIS
(151,'Adrian',     'San-Miguel',    'portero',   'D'),
(152,'Pau',        'Lopez',         'portero',   'D'),
(153,'Alex',       'Valles',        'portero',   'D'),
(154,'Hector',     'Bellerin',      'defensa',   'D'),
(155,'Diego',      'Llorente',      'defensa',   'D'),
(156,'Natan',      'De Souza',      'defensa',   'D'),
(157,'Marc',       'Bartra',        'defensa',   'D'),
(158,'Valentin',   'Gomez',         'defensa',   'D'),
(159,'Aitor',      'Ruibal',        'defensa',   'D'),
(160,'Ricardo',    'Rodriguez',     'defensa',   'Z'),
(161,'Junior',     'Firpo',         'defensa',   'Z'),
(162,'Sergi',      'Altimira',      'medio',     'D'),
(163,'Isco',       'Alarcon',       'medio',     'D'),
(164,'Sofyan',     'Amrabat',       'medio',     'D'),
(165,'Alex',       'Fidalgo',       'medio',     'D'),
(166,'Nelson',     'Deossa',        'medio',     'D'),
(167,'Marc',       'Roca',          'medio',     'D'),
(168,'Rodrigo',    'Riquelme',      'medio',     'D'),
(169,'Pablo',      'Fornals',       'medio',     'Z'),
(170,'Giovani',    'Lo Celso',      'medio',     'Z'),
(171,'Ezzalzouli', 'Abde',          'delantero', 'D'),
(172,'Cucho',      'Hernandez',     'delantero', 'D'),
(173,'Antony',     'Dos Santos',    'delantero', 'Z'),
(174,'Pablo',      'Garcia',        'delantero', 'Z'),
(175,'Cedric',     'Bakambu',       'delantero', 'D'),

-- SEVILLA FC
(176,'Orjan',      'Nyland',        'portero',   'D'),
(177,'Odysseas',   'Vlachodimos',   'portero',   'D'),
(178,'Cesar',      'Azpilicueta',   'defensa',   'D'),
(179,'Kike',       'Salas',         'defensa',   'Z'),
(180,'Marcao',     'Teixeira',      'defensa',   'D'),
(181,'Jose Angel', 'Carmona',       'defensa',   'D'),
(182,'Marcao',     'Teixeira',      'defensa',   'D'),
(183,'Tanguy',     'Nianzou',       'defensa',   'D'),
(184,'Gabriel',    'Suazzo',        'defensa',   'D'),
(185,'Fabio',      'Cardoso',       'defensa',   'D'),
(186,'Joaquin',    'Oso',           'defensa',   'D'),
(187,'Juanlu',     'Snachez',       'defensa',   'D'),
(188,'Nemanja',    'GUdelj',        'medio',     'D'),
(189,'Joan',       'Jordan',        'medio',     'D'),
(190,'Djibril',    'Sow',           'medio',     'D'),
(191,'Lucien',     'Agoume',        'medio',     'D'),
(192,'Gerard',     'Fernandez',     'medio',     'D'),
(193,'Batista',    'Mendy',         'medio',     'D'),
(194,'Isaac',      'Romero',        'delantero', 'Z'),
(195,'Alexis',     'Sanchez',       'delantero', 'Z'),
(196,'Akor',       'Adams',         'delantero', 'D'),
(197,'Rueben',     'Vargas',        'delantero', 'D'),
(198,'Chidera',    'Ejuke',         'delantero', 'D'),
(199,'Neal',       'Maupay',        'delantero', 'D'),
(200,'Adnan',      'Januzaj',       'delantero', 'D'),

-- RC CELTA DE VIGO
(86, 'Ivan',       'Villar',        'portero',   'D'),
(87, 'Kevin',      'Vazquez',       'defensa',   'D'),
(88, 'Unai',       'Nunez',         'defensa',   'Z'),
(89, 'Joseph',     'Aidoo',         'defensa',   'D'),
(90, 'Jailson',    'Marques',       'defensa',   'D'),
(91, 'Fran',       'Beltran',       'medio',     'D'),
(92, 'Oscar',      'Mingueza',      'defensa',   'D'),
(93, 'Luca',       'De La Torre',   'medio',     'D'),
(94, 'Iago',       'Aspas',         'delantero', 'Z'),
(95, 'Borja',      'Iglesias',      'delantero', 'D'),

-- GETAFE CF
(96,  'David',     'Soria',         'portero',   'D'),
(97,  'Stefan',    'Mitrovic',      'defensa',   'D'),
(98,  'Djene',     'Dakonam',       'defensa',   'D'),
(99,  'Juan',      'Iglesias',      'defensa',   'Z'),
(100, 'Damian',    'Suarez',        'defensa',   'D'),
(101, 'Mauro',     'Arambarri',     'medio',     'D'),
(102, 'Luis',      'Milla',         'medio',     'D'),
(103, 'Chema',     'Rodriguez',     'medio',     'D'),
(104, 'Borja',     'Mayoral',       'delantero', 'D'),
(105, 'Mason',     'Greenwood',     'delantero', 'D'),

-- RAYO VALLECANO
(106, 'Augusto',   'Batalla',       'portero',   'D'),
(107, 'Ivan',      'Balliu',        'defensa',   'D'),
(108, 'Florian',   'Lejeune',       'defensa',   'D'),
(109, 'Alejandro', 'Catena',        'defensa',   'D'),
(110, 'Martin',    'Fueentes',      'defensa',   'Z'),
(111, 'Oscar',     'Trejo',         'medio',     'D'),
(112, 'Jose',      'Pozo',          'medio',     'D'),
(113, 'Randy',     'Nteka',         'medio',     'D'),
(114, 'Raul',      'De Tomas',      'delantero', 'D'),
(115, 'Unai',      'Lopez',         'medio',     'Z'),

-- VALENCIA CF
(116, 'Giorgi',    'Mamardashvili', 'portero',   'D'),
(117, 'Thierry',   'Correia',       'defensa',   'D'),
(118, 'Cristhian', 'Mosquera',      'defensa',   'D'),
(119, 'Cenk',      'Ozkacar',       'defensa',   'D'),
(120, 'Jose Luis', 'Gaya',          'defensa',   'Z'),
(121, 'Andre',     'Almeida',       'medio',     'D'),
(122, 'Pepelu',    'Martinez',      'medio',     'D'),
(123, 'Justin',    'Kluivert',      'delantero', 'D'),
(124, 'Hugo',      'Duro',          'delantero', 'D'),
(125, 'Dani',      'Gomez',         'delantero', 'D'),

-- OSASUNA
(126, 'Sergio',    'Herrera',       'portero',   'D'),
(127, 'Nacho',     'Vidal',         'defensa',   'D'),
(128, 'David',     'Garcia',        'defensa',   'Z'),
(129, 'Aridane',   'Hernandez',     'defensa',   'D'),
(130, 'Juan Cruz',  'Oluwatosin',   'defensa',   'Z'),
(131, 'Lucas',     'Torro',         'medio',     'D'),
(132, 'Jon',       'Moncayola',     'medio',     'D'),
(133, 'Ante',      'Budimir',       'delantero', 'D'),
(134, 'Abde',      'Ezzalzouli',    'delantero', 'D'),
(135, 'Pablo',     'Ibanez',        'medio',     'D'),

-- MALLORCA
(136, 'Predrag',   'Rajkovic',      'portero',   'D'),
(137, 'Pablo',     'Maffeo',        'defensa',   'D'),
(138, 'Antonio',   'Raillo',        'defensa',   'D'),
(139, 'Martin',    'Valjent',       'defensa',   'D'),
(140, 'Jaume',     'Costa',         'defensa',   'Z'),
(141, 'Dani',      'Rodriguez',     'medio',     'D'),
(142, 'Antonio',   'Sanchez',       'medio',     'D'),
(143, 'Cyle',      'Larin',         'delantero', 'D'),
(144, 'Vedat',     'Muriqi',        'delantero', 'D'),
(145, 'Lee',       'Kang-In',       'delantero', 'D'),

-- GIRONA FC
(146, 'Paulo',     'Gazzaniga',     'portero',   'D'),
(147, 'Yan',       'Couto',         'defensa',   'D'),
(148, 'Ladislav',  'Krejci',        'defensa',   'Z'),
(149, 'Eric',      'Garcia',        'defensa',   'D'),
(150, 'Miguel',    'Gutierrez',     'defensa',   'Z'),
(151, 'Aleix',     'Garcia',        'medio',     'D'),
(152, 'Viktor',    'Tsyhankov',     'medio',     'D'),
(153, 'Artem',     'Dovbyk',        'delantero', 'D'),
(154, 'Savinho',   'Moreira',       'delantero', 'D'),
(155, 'Bryan',     'Gil',           'delantero', 'Z'),

-- ESPANYOL
(156, 'Joan',      'Garcia',        'portero',   'D'),
(157, 'Nathanael', 'Ogbeta',        'defensa',   'D'),
(158, 'Leandro',   'Cabrera',       'defensa',   'D'),
(159, 'Omar',      'El Hilali',     'defensa',   'D'),
(160, 'Gragory',   'Sertic',        'defensa',   'D'),
(161, 'Carlos',    'Romero',        'medio',     'D'),
(162, 'Jofre',     'Carreras',      'medio',     'D'),
(163, 'Javi',      'Puado',         'delantero', 'D'),
(164, 'Bojan',     'Krkic',         'delantero', 'D'),
(165, 'Dani',      'Galan',         'delantero', 'Z'),

-- LEGANES
(166, 'Ivan',      'Cuellar',       'portero',   'D'),
(167, 'Alejandro', 'Francés',       'defensa',   'D'),
(168, 'Sergio',    'Gonzalez',      'defensa',   'D'),
(169, 'Matija',    'Nastasic',      'defensa',   'D'),
(170, 'Jonathan',  'Silva',         'defensa',   'D'),
(171, 'Darko',     'Brasanac',      'medio',     'D'),
(172, 'Nemanja',   'Maksimovic',    'medio',     'D'),
(173, 'Óscar',     'Rodriguez',     'medio',     'D'),
(174, 'Munir',     'El Haddadi',    'delantero', 'D'),
(175, 'Yvan',      'Neyou',         'medio',     'D'),

-- ALAVES
(176, 'Antonio',   'Sivera',        'portero',   'D'),
(177, 'Ruben',     'Duarte',        'defensa',   'Z'),
(178, 'Victor',    'Laguardia',     'defensa',   'D'),
(179, 'Florian',   'Diaby',         'defensa',   'Z'),
(180, 'Luis',      'Rioja',         'defensa',   'Z'),
(181, 'Pablo',     'Fofolrinho',    'medio',     'D'),
(182, 'Manu',      'Sanchez',       'defensa',   'Z'),
(183, 'Ximo',      'Navarro',       'defensa',   'D'),
(184, 'Toni',      'Martinez',      'delantero', 'D'),
(185, 'Kike',      'Garcia',        'delantero', 'D'),

-- VALLADOLID
(186, 'Jordi',     'Masip',         'portero',   'D'),
(187, 'Ivan',      'Sanchez',       'defensa',   'D'),
(188, 'Waldo',     'Rubio',         'defensa',   'D'),
(189, 'Jawad',     'El Yamiq',      'defensa',   'D'),
(190, 'Roque',     'Mesa',          'medio',     'D'),
(191, 'Ramon',     'Terrats',       'medio',     'D'),
(192, 'Anuar',     'Mohamed',       'medio',     'D'),
(193, 'Luis',      'Perez',         'delantero', 'D'),
(194, 'Selim',     'Amallah',       'delantero', 'D'),
(195, 'Sergio',    'Leon',          'delantero', 'D'),

-- GRANADA CF
(196, 'Louis',     'Maximiano',     'portero',   'D'),
(197, 'Ricard',    'Sanchez',       'defensa',   'D'),
(198, 'Ignasi',    'Miquel',        'defensa',   'D'),
(199, 'Miguel',    'Rubio',         'defensa',   'D'),
(200, 'Carlos',    'Neva',          'defensa',   'Z'),
(201, 'Myrto',     'Uzuni',         'delantero', 'D'),
(202, 'Bryan',     'Zaragoza',      'delantero', 'D'),
(203, 'Lucas',     'Boyé',          'delantero', 'D'),
(204, 'Sergio',    'Ruiz',          'medio',     'D'),
(205, 'Alberto',   'Perea',         'medio',     'D');