DROP DATABASE IF EXISTS futbol;
CREATE DATABASE IF NOT EXISTS futbol;
USE futbol;

create table equipo (
id_ciudad int,
id int primary key,
nombre varchar(50),
fecha_fundacion date,
nombre_campo varchar(50)
);

create table jugador (
id int primary key,
nombre varchar(50),
apellido varchar(50),
posicion varchar(10) check (posicion IN ('portero', 'defensa', 'medio', 'delantero')),
pierna_habil char check (pierna_habil IN ('D', 'Z', 'A'))
);

create table ciudad (
id int primary key,
nombre varchar(50),
jugador_natal boolean
);

create table equipo_jugador (
id int primary key auto_increment,
id_equipo int,
id_jugador int,
fecha_inicio DATE,
fecha_fin DATE,
dorsal INT check (dorsal between 1 AND 50)
);

ALTER TABLE equipo_jugador add constraint fk_jugador foreign key (id_jugador) references jugador (id);
ALTER TABLE equipo_jugador add constraint fk_equipo foreign key (id_equipo) references equipo (id);
ALTER TABLE equipo add constraint fk_ciudad foreign key (id_ciudad) references ciudad (id);

INSERT INTO ciudad (id, nombre) VALUES
(1, 'Madrid'),
(2, 'Barcelona'),
(3, 'Sevilla'),
(4, 'San Sebastián'),
(5, 'Bilbao'),
(6, 'Villarreal'),
(7, 'Valencia'),
(8, 'Getafe'),
(9, 'Vigo'),
(10, 'Pamplona'),
(11, 'Las Palmas de Gran Canaria'),
(12, 'Palma de Mallorca'),
(13, 'Girona'),
(14, 'Vitoria-Gasteiz'),
(15, 'Cádiz'),
(16, 'Granada'),
(17, 'Valladolid');

INSERT INTO equipo (id_ciudad, id, nombre, fecha_fundacion, nombre_campo) VALUES
(1, 1, 'Real Madrid', '1902-03-06', 'Santiago Bernabéu'),
(2, 2, 'FC Barcelona', '1899-11-29', 'Spotify Camp Nou'),
(1, 3, 'Atlético de Madrid', '1903-04-26', 'Cívitas Metropolitano'),
(3, 4, 'Sevilla FC', '1890-01-25', 'Ramón Sánchez-Pizjuán'),
(3, 5, 'Real Betis', '1907-09-12', 'Benito Villamarín'),
(4, 6, 'Real Sociedad', '1909-09-07', 'Reale Arena'),
(5, 7, 'Athletic Club', '1898-01-01', 'San Mamés'),
(6, 8, 'Villarreal CF', '1923-03-10', 'La Cerámica'),
(7, 9, 'Valencia CF', '1919-03-18', 'Mestalla'),
(8, 10, 'Getafe CF', '1983-03-30', 'Coliseum'),
(9, 11, 'RC Celta', '1923-08-23', 'Abanca Balaídos'),
(10, 12, 'CA Osasuna', '1920-10-24', 'El Sadar'),
(1, 13, 'Rayo Vallecano', '1924-05-29', 'Vallecas'),
(11, 14, 'UD Las Palmas', '1949-08-22', 'Gran Canaria'),
(12, 15, 'RCD Mallorca', '1916-03-05', 'Son Moix'),
(13, 16, 'Girona FC', '1930-07-23', 'Montilivi'),
(14, 17, 'Deportivo Alavés', '1921-01-23', 'Mendizorroza'),
(15, 18, 'Cádiz CF', '1910-09-10', 'Nuevo Mirandilla'),
(16, 19, 'Granada CF', '1931-04-14', 'Los Cármenes'),
(17, 20, 'Real Valladolid', '1928-06-20', 'José Zorrilla');

INSERT INTO jugador (id, nombre, apellido, posicion, pierna_habil) VALUES

-- ============================================================
-- 1. REAL MADRID (entrenador: Xabi Alonso)
-- ============================================================
(1,  'Thibaut',    'Courtois',          'portero',   'D'),
(2,  'Andriy',     'Lunin',             'portero',   'D'),
(3,  'Dani',       'Carvajal',          'defensa',   'D'),
(4,  'Eder',       'Militao',           'defensa',   'D'),
(5,  'David',      'Alaba',             'defensa',   'Z'),
(6,  'Trent',      'Alexander-Arnold',  'defensa',   'D'),
(7,  'Raul',       'Asencio',           'defensa',   'D'),
(8,  'Alvaro',     'Carreras',          'defensa',   'Z'),
(9,  'Fran',       'Garcia',            'defensa',   'Z'),
(10, 'Antonio',    'Rudiger',           'defensa',   'D'),
(11, 'Ferland',    'Mendy',             'defensa',   'Z'),
(12, 'Dean',       'Huijsen',           'defensa',   'D'),
(13, 'Jude',       'Bellingham',        'medio',     'D'),
(14, 'Eduardo',    'Camavinga',         'medio',     'Z'),
(15, 'Federico',   'Valverde',          'medio',     'D'),
(16, 'Aurelien',   'Tchouameni',        'medio',     'D'),
(17, 'Arda',       'Guler',             'medio',     'D'),
(18, 'Dani',       'Ceballos',          'medio',     'D'),
(19, 'Brahim',     'Diaz',              'medio',     'D'),
(20, 'Franco',     'Mastantuono',       'medio',     'D'),
(21, 'Vinicius',   'Junior',            'delantero', 'D'),
(22, 'Endrick',    'Felipe',            'delantero', 'D'),
(23, 'Kylian',     'Mbappe',            'delantero', 'D'),
(24, 'Rodrygo',    'Goes',              'delantero', 'D'),
(25, 'Gonzalo',    'Garcia',            'delantero', 'D'),

-- ============================================================
-- 2. FC BARCELONA (entrenador: Hansi Flick)
-- ============================================================
(26, 'Wojciech',   'Szczesny',          'portero',   'D'),
(27, 'Inaki',      'Pena',              'portero',   'D'),
(28, 'Jules',      'Kounde',            'defensa',   'D'),
(29, 'Ronald',     'Araujo',            'defensa',   'D'),
(30, 'Pau',        'Cubarsi',           'defensa',   'Z'),
(31, 'Alejandro',  'Balde',             'defensa',   'Z'),
(32, 'Eric',       'Garcia',            'defensa',   'D'),
(33, 'Gerard',     'Martin',            'defensa',   'Z'),
(34, 'Pedri',      'Gonzalez',          'medio',     'D'),
(35, 'Frenkie',    'De Jong',           'medio',     'D'),
(36, 'Marc',       'Casado',            'medio',     'D'),
(37, 'Dani',       'Olmo',              'medio',     'D'),
(38, 'Fermin',     'Lopez',             'medio',     'D'),
(39, 'Marcus',     'Rashford',          'medio',     'D'),
(40, 'Pau',        'Victor',            'medio',     'D'),
(41, 'Lamine',     'Yamal',             'delantero', 'D'),
(42, 'Robert',     'Lewandowski',       'delantero', 'D'),
(43, 'Raphinha',   'Belloli',           'delantero', 'D'),
(44, 'Ferran',     'Torres',            'delantero', 'D'),
(45, 'Ansu',       'Fati',              'delantero', 'D'),
(46, 'Gavi',       'Paez',              'medio',     'D'),
(47, 'Andreas',    'Christensen',       'defensa',   'D'),
(48, 'Hector',     'Fort',              'defensa',   'D'),
(49, 'Inigo',      'Martinez',          'defensa',   'Z'),
(50, 'Noah',       'Darvich',           'delantero', 'D'),

-- ============================================================
-- 3. ATLETICO DE MADRID (entrenador: Diego Simeone)
-- ============================================================
(51, 'Juan',       'Musso',             'portero',   'D'),
(52, 'Jan',        'Oblak',             'portero',   'D'),
(53, 'Jose Maria', 'Gimenez',           'defensa',   'D'),
(54, 'Matteo',     'Ruggeri',           'defensa',   'Z'),
(55, 'Nahuel',     'Molina',            'defensa',   'D'),
(56, 'David',      'Hancko',            'defensa',   'Z'),
(57, 'Marc',       'Pubill',            'defensa',   'D'),
(58, 'Clement',    'Lenglet',           'defensa',   'Z'),
(59, 'Robin',      'Le Normand',        'defensa',   'D'),
(60, 'Koke',       'Resurreccion',      'medio',     'D'),
(61, 'Pablo',      'Barrios',           'medio',     'D'),
(62, 'Johnny',     'Cardoso',           'medio',     'D'),
(63, 'Rodrigo',    'Mendoza',           'medio',     'D'),
(64, 'Marcos',     'Llorente',          'medio',     'D'),
(65, 'Thiago',     'Almada',            'medio',     'D'),
(66, 'Alex',       'Baena',             'medio',     'D'),
(67, 'Rodrigo',    'De Paul',           'medio',     'D'),
(68, 'Antoine',    'Griezmann',         'delantero', 'D'),
(69, 'Julian',     'Alvarez',           'delantero', 'D'),
(70, 'Alexander',  'Sorloth',           'delantero', 'D'),
(71, 'Samuel',     'Lino',              'delantero', 'Z'),
(72, 'Angel',      'Correa',            'delantero', 'D'),
(73, 'Conor',      'Gallagher',         'medio',     'D'),
(74, 'Ivan',       'Llorente',          'defensa',   'D'),
(75, 'Javi',       'Serrano',           'defensa',   'Z'),

-- ============================================================
-- 4. ATHLETIC CLUB (entrenador: Ernesto Valverde)
-- ============================================================
(76, 'Julen',      'Agirrezabala',      'portero',   'D'),
(77, 'Unai',       'Simon',             'portero',   'D'),
(78, 'Oscar',      'De Marcos',         'defensa',   'D'),
(79, 'Dani',       'Vivian',            'defensa',   'D'),
(80, 'Aitor',      'Paredes',           'defensa',   'D'),
(81, 'Yuri',       'Berchiche',         'defensa',   'Z'),
(82, 'Mikel',      'Jauregizar',        'defensa',   'D'),
(83, 'Andoni',     'Gorosabel',         'defensa',   'D'),
(84, 'Yeray',      'Alvarez',           'defensa',   'D'),
(85, 'Mikel',      'Vesga',             'medio',     'D'),
(86, 'Oihan',      'Sancet',            'medio',     'D'),
(87, 'Ander',      'Herrera',           'medio',     'D'),
(88, 'Unai',       'Gomez',             'medio',     'D'),
(89, 'Peru',       'Nolaskoain',        'medio',     'D'),
(90, 'Benat',      'Prados',            'medio',     'D'),
(91, 'Jon',        'Morcillo',          'medio',     'D'),
(92, 'Mikel',      'Balenziaga',        'defensa',   'Z'),
(93, 'Nico',       'Williams',          'delantero', 'D'),
(94, 'Inaki',      'Williams',          'delantero', 'D'),
(95, 'Gorka',      'Guruzeta',          'delantero', 'D'),
(96, 'Asier',      'Villalibre',        'delantero', 'D'),
(97, 'Luka',       'Susaeta',           'delantero', 'D'),
(98, 'Alex',       'Petxarroman',       'defensa',   'D'),
(99, 'Iker',       'Muniain',           'medio',     'D'),
(100,'Unai',       'Nunez',             'defensa',   'D'),

-- ============================================================
-- 5. VILLARREAL CF (entrenador: Marcelino / Quique Setien)
-- ============================================================
(101,'Diego',      'Conde',             'portero',   'D'),
(102,'Filip',      'Jorgensen',         'portero',   'D'),
(103,'Juan',       'Foyth',             'defensa',   'D'),
(104,'Alfonso',    'Pedraza',           'defensa',   'Z'),
(105,'Pau',        'Torres',            'defensa',   'Z'),
(106,'Eric',       'Bailly',            'defensa',   'D'),
(107,'Aissa',      'Mandi',             'defensa',   'D'),
(108,'Alberto',    'Moreno',            'defensa',   'Z'),
(109,'Serge',      'Aurier',            'defensa',   'D'),
(110,'Dani',       'Parejo',            'medio',     'D'),
(111,'Etienne',    'Capoue',            'medio',     'D'),
(112,'Samu',       'Chukwueze',         'medio',     'D'),
(113,'Ilias',      'Akhomach',          'medio',     'D'),
(114,'Nicolas',    'Pepe',              'medio',     'D'),
(115,'Yeremy',     'Pino',              'delantero', 'D'),
(116,'Gerard',     'Moreno',            'delantero', 'D'),
(117,'Arnaut',     'Danjuma',           'delantero', 'D'),
(118,'Pepe',       'Reina',             'portero',   'D'),
(119,'Raul',       'Albiol',            'defensa',   'D'),
(120,'Thierno',    'Barry',             'delantero', 'D'),
(121,'Jorge',      'Cuenca',            'defensa',   'Z'),
(122,'Ilias',      'Morales',           'medio',     'D'),
(123,'Pepelu',     'Martinez',          'medio',     'D'),
(124,'Kiko',       'Femenia',           'defensa',   'D'),
(125,'Jose Luis',  'Morales',           'delantero', 'Z'),

-- ============================================================
-- 6. REAL SOCIEDAD (entrenador: Imanol Alguacil)
-- ============================================================
(126,'Alex',       'Remiro',            'portero',   'D'),
(127,'Andres',     'Fernandez',         'portero',   'D'),
(128,'Andoni',     'Gorosabel',         'defensa',   'D'),
(129,'Igor',       'Zubeldia',          'defensa',   'D'),
(130,'Aritz',      'Elustondo',         'defensa',   'D'),
(131,'Aihen',      'Munoz',             'defensa',   'Z'),
(132,'Jon',        'Aramburu',          'defensa',   'D'),
(133,'Hamari',     'Traore',            'defensa',   'D'),
(134,'Nayef',      'Aguerd',            'defensa',   'D'),
(135,'Luca',       'Sucic',             'medio',     'D'),
(136,'Brais',      'Mendez',            'medio',     'D'),
(137,'Asier',      'Illarramendi',      'medio',     'D'),
(138,'Benat',      'Turrientes',        'medio',     'D'),
(139,'Robert',     'Navarro',           'medio',     'D'),
(140,'Sergio',     'Gomez',             'defensa',   'Z'),
(141,'Mikel',      'Oyarzabal',         'delantero', 'Z'),
(142,'Takefusa',   'Kubo',              'delantero', 'D'),
(143,'Umar',       'Sadiq',             'delantero', 'D'),
(144,'Sheraldo',   'Becker',            'delantero', 'D'),
(145,'Carlos',     'Fernandez',         'delantero', 'D'),
(146,'Andre',      'Silva',             'delantero', 'D'),
(147,'Mohamed',    'Cho',               'delantero', 'D'),
(148,'Pablo',      'Marin',             'medio',     'D'),
(149,'Ander',      'Barrenetxea',       'delantero', 'Z'),
(150,'Jon',        'Pacheco',           'portero',   'D'),

-- ============================================================
-- 7. REAL BETIS (entrenador: Manuel Pellegrini)
-- ============================================================
(151,'Rui',        'Silva',             'portero',   'D'),
(152,'Fran',       'Vieites',           'portero',   'D'),
(153,'Hector',     'Bellerin',          'defensa',   'D'),
(154,'Natan',      'De Souza',          'defensa',   'D'),
(155,'Marc',       'Bartra',            'defensa',   'D'),
(156,'Ricardo',    'Rodriguez',         'defensa',   'Z'),
(157,'Pablo',      'Fornals',           'medio',     'Z'),
(158,'Giovani',    'Lo Celso',          'medio',     'Z'),
(159,'Isco',       'Alarcon',           'medio',     'D'),
(160,'Guido',      'Rodriguez',         'medio',     'D'),
(161,'William',    'Carvalho',          'medio',     'D'),
(162,'Sergi',      'Altimira',          'medio',     'D'),
(163,'Dani',       'Avila',             'medio',     'D'),
(164,'Romain',     'Perraud',           'defensa',   'Z'),
(165,'Juanmi',     'Jimenez',           'delantero', 'D'),
(166,'Ayoze',      'Perez',             'delantero', 'D'),
(167,'Vitor',      'Roque',             'delantero', 'D'),
(168,'Antony',     'Matheus',           'delantero', 'D'),
(169,'Ez',         'Abde',              'delantero', 'Z'),
(170,'Cedric',     'Bakambu',           'delantero', 'D'),
(171,'Diego',      'Llorente',          'defensa',   'D'),
(172,'German',     'Pezzella',          'defensa',   'D'),
(173,'Chadi',      'Riad',              'defensa',   'Z'),
(174,'Johnny',     'Cardoso',           'medio',     'D'),
(175,'Jesus',      'Rodriguez',         'medio',     'D'),

-- ============================================================
-- 8. SEVILLA FC (entrenador: Xavi Garcia Pimienta)
-- ============================================================
(176,'Orjan',      'Nyland',            'portero',   'D'),
(177,'Alfonso',    'Pastor',            'portero',   'D'),
(178,'Jesus',      'Navas',             'defensa',   'D'),
(179,'Loic',       'Bade',              'defensa',   'D'),
(180,'Marcao',     'Teixeira',          'defensa',   'D'),
(181,'Marcos',     'Acuna',             'defensa',   'Z'),
(182,'Juanlu',     'Sanchez',           'defensa',   'D'),
(183,'Nianzou',    'Kouassi',           'defensa',   'D'),
(184,'Kike',       'Salas',             'defensa',   'D'),
(185,'Fernando',   'Reges',             'medio',     'D'),
(186,'Samu',       'Acosta',            'medio',     'D'),
(187,'Lucien',     'Agoume',            'medio',     'D'),
(188,'Ivan',       'Marcano',           'defensa',   'D'),
(189,'Dodi',       'Lukebakio',         'delantero', 'D'),
(190,'Chidera',    'Ejuke',             'delantero', 'D'),
(191,'Isaac',      'Romero',            'delantero', 'D'),
(192,'Youssef',    'En-Nesyri',         'delantero', 'D'),
(193,'Victor',     'Noriega',           'delantero', 'D'),
(194,'Rafa',       'Mir',               'delantero', 'D'),
(195,'Peque',      'Fernandez',         'medio',     'D'),
(196,'Jose Angel', 'Carmona',           'defensa',   'D'),
(197,'Karim',      'Rekik',             'defensa',   'Z'),
(198,'Alberto',    'Flores',            'medio',     'D'),
(199,'Erik',       'Lamela',            'medio',     'D'),
(200,'Adria',      'Pedrosa',           'defensa',   'Z'),

-- ============================================================
-- 9. RC CELTA DE VIGO (entrenador: Claudio Giráldez)
-- ============================================================
(201,'Ivan',       'Villar',            'portero',   'D'),
(202,'Vicente',    'Guaita',            'portero',   'D'),
(203,'Kevin',      'Vazquez',           'defensa',   'D'),
(204,'Unai',       'Nunez',             'defensa',   'Z'),
(205,'Joseph',     'Aidoo',             'defensa',   'D'),
(206,'Carlos',     'Dominguez',         'defensa',   'D'),
(207,'Oscar',      'Mingueza',          'defensa',   'D'),
(208,'Hugo',       'Alvarez',           'defensa',   'D'),
(209,'Jailson',    'Marques',           'defensa',   'D'),
(210,'Fran',       'Beltran',           'medio',     'D'),
(211,'Luca',       'De La Torre',       'medio',     'D'),
(212,'Carles',     'Perez',             'medio',     'D'),
(213,'Williot',    'Swedberg',          'medio',     'D'),
(214,'Gabri',      'Veiga',             'medio',     'D'),
(215,'Miguel',     'Rodriguez',         'medio',     'D'),
(216,'Iago',       'Aspas',             'delantero', 'Z'),
(217,'Jonathan',   'Bamba',             'delantero', 'D'),
(218,'Borja',      'Iglesias',          'delantero', 'D'),
(219,'Anastasios', 'Douvikas',          'delantero', 'D'),
(220,'Alfon',      'Gonzalez',          'medio',     'D'),
(221,'Jorge',      'Saenz',             'defensa',   'D'),
(222,'Franco',     'Cervi',             'delantero', 'Z'),
(223,'Patrick',    'Emond',             'delantero', 'D'),
(224,'Agustin',    'Marchesin',         'portero',   'D'),
(225,'Javier',     'Manquillo',         'defensa',   'D'),

-- ============================================================
-- 10. GETAFE CF (entrenador: José Bordalás)
-- ============================================================
(226,'David',      'Soria',             'portero',   'D'),
(227,'Alfonso',    'Herrero',           'portero',   'D'),
(228,'Stefan',     'Mitrovic',          'defensa',   'D'),
(229,'Djene',      'Dakonam',           'defensa',   'D'),
(230,'Damian',     'Suarez',            'defensa',   'D'),
(231,'Omar',       'Alderete',          'defensa',   'D'),
(232,'Mathias',    'Olivera',           'defensa',   'Z'),
(233,'Gastón',     'Alvarez',           'defensa',   'D'),
(234,'Jesus',      'Forsberg',          'defensa',   'D'),
(235,'Mauro',      'Arambarri',         'medio',     'D'),
(236,'Luis',       'Milla',             'medio',     'D'),
(237,'Carles',     'Alena',             'medio',     'D'),
(238,'Oscar',      'Rodriguez',         'medio',     'D'),
(239,'Chema',      'Rodriguez',         'medio',     'D'),
(240,'Portu',      'Sanahuja',          'medio',     'D'),
(241,'Nemanja',    'Maksimovic',        'medio',     'D'),
(242,'Borja',      'Mayoral',           'delantero', 'D'),
(243,'Mason',      'Greenwood',         'delantero', 'D'),
(244,'Jaime',      'Mata',              'delantero', 'D'),
(245,'Enes',       'Unal',              'delantero', 'D'),
(246,'Juanmi',     'Latasa',            'delantero', 'D'),
(247,'Juan',       'Iglesias',          'defensa',   'D'),
(248,'Jorge',      'Cuenca',            'defensa',   'Z'),
(249,'Diego',      'Rico',              'defensa',   'Z'),
(250,'Florian',    'Neuhaus',           'medio',     'D'),

-- ============================================================
-- 11. RAYO VALLECANO (entrenador: Iñigo Pérez)
-- ============================================================
(251,'Augusto',    'Batalla',           'portero',   'D'),
(252,'Stole',      'Dimitrievski',      'portero',   'D'),
(253,'Ivan',       'Balliu',            'defensa',   'D'),
(254,'Florian',    'Lejeune',           'defensa',   'D'),
(255,'Alejandro',  'Catena',            'defensa',   'D'),
(256,'Fran',       'Garcia',            'defensa',   'Z'),
(257,'Mario',      'Suarez',            'defensa',   'D'),
(258,'Sergio',     'Camello',           'defensa',   'D'),
(259,'Niels',      'Nkounkou',          'defensa',   'Z'),
(260,'Oscar',      'Trejo',             'medio',     'D'),
(261,'Unai',       'Lopez',             'medio',     'Z'),
(262,'Jose',       'Pozo',              'medio',     'D'),
(263,'Randy',      'Nteka',             'medio',     'D'),
(264,'Pathe',      'Ciss',              'medio',     'D'),
(265,'Jorge',      'De Frutos',         'medio',     'D'),
(266,'Oscar',      'Valentín',          'medio',     'D'),
(267,'Raul',       'De Tomas',          'delantero', 'D'),
(268,'Alvaro',     'Garcia',            'delantero', 'D'),
(269,'Sergio',     'Leon',              'delantero', 'D'),
(270,'Luca',       'Zidane',            'portero',   'D'),
(271,'Andres',     'Martin',            'medio',     'D'),
(272,'Isi',        'Palazon',           'delantero', 'D'),
(273,'Bebeto',     'Andrean',           'delantero', 'D'),
(274,'Jose Maria', 'Salvi',             'defensa',   'D'),
(275,'Abdel',      'Abqar',             'medio',     'D'),

-- ============================================================
-- 12. VALENCIA CF (entrenador: Carlos Corberán)
-- ============================================================
(276,'Giorgi',     'Mamardashvili',     'portero',   'D'),
(277,'Jaume',      'Domenech',          'portero',   'D'),
(278,'Thierry',    'Correia',           'defensa',   'D'),
(279,'Cristhian',  'Mosquera',          'defensa',   'D'),
(280,'Cenk',       'Ozkacar',           'defensa',   'D'),
(281,'Jose Luis',  'Gaya',              'defensa',   'Z'),
(282,'Mouctar',    'Diakhaby',          'defensa',   'D'),
(283,'Hugo',       'Guillamon',         'defensa',   'D'),
(284,'Diego',      'Lopez',             'defensa',   'D'),
(285,'Andre',      'Almeida',           'medio',     'D'),
(286,'Pepelu',     'Martinez',          'medio',     'D'),
(287,'Javi',       'Guerra',            'medio',     'D'),
(288,'Cesar',      'Tarrega',           'medio',     'D'),
(289,'Yarek',      'Gasiorowski',       'defensa',   'D'),
(290,'Selim',      'Amallah',           'medio',     'D'),
(291,'Justin',     'Kluivert',          'delantero', 'D'),
(292,'Hugo',       'Duro',              'delantero', 'D'),
(293,'Dani',       'Gomez',             'delantero', 'D'),
(294,'Diego',      'Lopez',             'medio',     'D'),
(295,'Rafa',       'Mir',               'delantero', 'D'),
(296,'Alejandro',  'Nieto',             'medio',     'D'),
(297,'Sergi',      'Canos',             'delantero', 'D'),
(298,'Eray',       'Comert',            'defensa',   'D'),
(299,'Fran',       'Perez',             'delantero', 'D'),
(300,'Nico',       'Gonzalez',          'medio',     'D'),

-- ============================================================
-- 13. CA OSASUNA (entrenador: Alessio Lisci)
-- ============================================================
(301,'Sergio',     'Herrera',           'portero',   'D'),
(302,'Aitor',      'Fernandez',         'portero',   'D'),
(303,'Nacho',      'Vidal',             'defensa',   'D'),
(304,'David',      'Garcia',            'defensa',   'Z'),
(305,'Aridane',    'Hernandez',         'defensa',   'D'),
(306,'Juan Cruz',  'Oluwatosin',        'defensa',   'Z'),
(307,'Alejandro',  'Catena',            'defensa',   'D'),
(308,'Kike',       'Barja',             'medio',     'D'),
(309,'Lucas',      'Torro',             'medio',     'D'),
(310,'Jon',        'Moncayola',         'medio',     'D'),
(311,'Pablo',      'Ibanez',            'medio',     'D'),
(312,'Ruben',      'Garcia',            'medio',     'D'),
(313,'Bryan',      'Zaragoza',          'medio',     'D'),
(314,'Abde',       'Ezzalzouli',        'delantero', 'D'),
(315,'Ante',       'Budimir',           'delantero', 'D'),
(316,'Jesus',      'Areso',             'defensa',   'D'),
(317,'Moi',        'Gomez',             'medio',     'Z'),
(318,'Patrick',    'Sondre',            'medio',     'D'),
(319,'Ezequiel',   'AvilesMeza',        'medio',     'D'),
(320,'Alberto',    'Flores',            'medio',     'D'),
(321,'Jorge',      'Herrando',          'defensa',   'D'),
(322,'Arnau',      'Danjuma',           'delantero', 'D'),
(323,'Chimy',      'Avila',             'delantero', 'D'),
(324,'Jonjon',     'Boyomo',            'defensa',   'D'),
(325,'Nicolas',    'Seibt',             'portero',   'D'),

-- ============================================================
-- 14. RCD MALLORCA (entrenador: Martín Demichelis)
-- ============================================================
(326,'Predrag',    'Rajkovic',          'portero',   'D'),
(327,'Leo',        'Roman',             'portero',   'D'),
(328,'Pablo',      'Maffeo',            'defensa',   'D'),
(329,'Antonio',    'Raillo',            'defensa',   'D'),
(330,'Martin',     'Valjent',           'defensa',   'D'),
(331,'Jaume',      'Costa',             'defensa',   'Z'),
(332,'Takuma',     'Asano',             'delantero', 'D'),
(333,'Brian',      'Oliván',            'defensa',   'D'),
(334,'Mateu',      'Morey',             'defensa',   'D'),
(335,'Dani',       'Rodriguez',         'medio',     'D'),
(336,'Antonio',    'Sanchez',           'medio',     'D'),
(337,'Samú',       'Costa',             'medio',     'D'),
(338,'Cyle',       'Larin',             'delantero', 'D'),
(339,'Vedat',      'Muriqi',            'delantero', 'D'),
(340,'Lee',        'Kang-In',           'delantero', 'D'),
(341,'Sergi',      'Darder',            'medio',     'D'),
(342,'Jose Luis',  'Morales',           'delantero', 'Z'),
(343,'Clement',    'Grenier',           'medio',     'D'),
(344,'David',      'Larrubia',          'delantero', 'D'),
(345,'Giovanni',   'Gonzalez',          'defensa',   'D'),
(346,'Alex',       'Sureda',            'medio',     'D'),
(347,'Omar',       'Mascarell',         'medio',     'D'),
(348,'Baba',       'Rahman',            'defensa',   'Z'),
(349,'Abdón',      'Prats',             'delantero', 'D'),
(350,'Dominic',    'Greif',             'portero',   'D'),

-- ============================================================
-- 15. GIRONA FC (entrenador: Míchel)
-- ============================================================
(351,'Paulo',      'Gazzaniga',         'portero',   'D'),
(352,'Juan Carlos', 'Martin',           'portero',   'D'),
(353,'Yan',        'Couto',             'defensa',   'D'),
(354,'Ladislav',   'Krejci',            'defensa',   'Z'),
(355,'Eric',       'Garcia',            'defensa',   'D'),
(356,'Miguel',     'Gutierrez',         'defensa',   'Z'),
(357,'David',      'Lopez',             'defensa',   'D'),
(358,'Santiago',   'Bueno',             'defensa',   'D'),
(359,'Victor',     'Tsygankov',         'medio',     'D'),
(360,'Oriol',      'Romeu',             'medio',     'D'),
(361,'Aleix',      'Garcia',            'medio',     'D'),
(362,'Yangel',     'Herrera',           'medio',     'D'),
(363,'Ivan',       'Martin',            'medio',     'D'),
(364,'Bryan',      'Gil',               'delantero', 'Z'),
(365,'Cristhian',  'Stuani',            'delantero', 'D'),
(366,'Savinho',    'Moreira',           'delantero', 'D'),
(367,'Arnaut',     'Danjuma',           'delantero', 'D'),
(368,'Bojan',      'Miovski',           'delantero', 'D'),
(369,'Gabriel',    'Misehouy',          'medio',     'D'),
(370,'Abel',       'Ruiz',              'delantero', 'D'),
(371,'Jhon',       'Solis',             'defensa',   'D'),
(372,'Paulo',      'Fernandes',         'medio',     'D'),
(373,'Toni',       'Villa',             'delantero', 'D'),
(374,'Donny',      'Van de Beek',       'medio',     'D'),
(375,'Alejandro',  'Frances',           'defensa',   'D'),

-- ============================================================
-- 16. RCD ESPANYOL (entrenador: Manolo González)
-- ============================================================
(376,'Joan',       'Garcia',            'portero',   'D'),
(377,'Carlos',     'Lopez',             'portero',   'D'),
(378,'Nathanael',  'Ogbeta',            'defensa',   'D'),
(379,'Leandro',    'Cabrera',           'defensa',   'D'),
(380,'Omar',       'El Hilali',         'defensa',   'D'),
(381,'Carlos',     'Romero',            'defensa',   'D'),
(382,'Didac',      'Vila',              'defensa',   'Z'),
(383,'Sergi',      'Gomez',             'defensa',   'D'),
(384,'Brian',      'Olivan',            'defensa',   'D'),
(385,'Carlos',     'Alcaraz',           'medio',     'D'),
(386,'Jofre',      'Carreras',          'medio',     'D'),
(387,'Martin',     'Braithwaite',       'delantero', 'D'),
(388,'Luis',       'Rioja',             'medio',     'Z'),
(389,'Alex',       'Domingo',           'medio',     'D'),
(390,'Pol',        'Lozano',            'medio',     'D'),
(391,'Javi',       'Puado',             'delantero', 'D'),
(392,'Dani',       'Galan',             'delantero', 'Z'),
(393,'Pere',       'Milla',             'delantero', 'D'),
(394,'Vini',       'Souza',             'medio',     'D'),
(395,'Alejo',      'Veliz',             'delantero', 'D'),
(396,'David',      'Lopez',             'defensa',   'D'),
(397,'Laia',       'Aleixandri',        'defensa',   'D'),
(398,'Lamine',     'Diarra',            'medio',     'D'),
(399,'Andres',     'Prieto',            'portero',   'D'),
(400,'Joselu',     'Mato',              'delantero', 'D'),

-- ============================================================
-- 17. DEPORTIVO ALAVES (entrenador: Eduardo Coudet)
-- ============================================================
(401,'Antonio',    'Sivera',            'portero',   'D'),
(402,'Sivera',     'Backup',            'portero',   'D'),
(403,'Ruben',      'Duarte',            'defensa',   'Z'),
(404,'Victor',     'Laguardia',         'defensa',   'D'),
(405,'Florian',    'Lejeune',           'defensa',   'D'),
(406,'Toni',       'Moya',              'medio',     'D'),
(407,'Manu',       'Sanchez',           'defensa',   'Z'),
(408,'Ximo',       'Navarro',           'defensa',   'D'),
(409,'Jon',        'Guridi',            'medio',     'D'),
(410,'Luis',       'Rioja',             'delantero', 'Z'),
(411,'Theo',       'Zidane',            'defensa',   'D'),
(412,'Pere',       'Pons',              'medio',     'D'),
(413,'Deyverson',  'Acosta',            'delantero', 'D'),
(414,'Toni',       'Martinez',          'delantero', 'D'),
(415,'Kike',       'Garcia',            'delantero', 'D'),
(416,'Carlos',     'Vicente',           'delantero', 'D'),
(417,'Samu',       'Gomez',             'medio',     'D'),
(418,'Sergio',     'Lozano',            'medio',     'D'),
(419,'Jon',        'Arrizabalaga',      'portero',   'D'),
(420,'Conechny',   'Saul',              'medio',     'D'),
(421,'Abqar',      'Abdel',             'medio',     'D'),
(422,'Jacob',      'Bruun',             'delantero', 'D'),
(423,'Sedlar',     'Aleksandar',        'defensa',   'D'),
(424,'Facundo',    'Pellistri',         'delantero', 'D'),
(425,'Carlos',     'Benavidez',         'medio',     'D'),

-- ============================================================
-- 18. REAL OVIEDO (entrenador: Guillermo Almada)
--     (ascendido tras 24 años en Segunda)
-- ============================================================
(426,'Alfonso',    'Herrero',           'portero',   'D'),
(427,'Gaspar',     'Campos',            'portero',   'D'),
(428,'Dani',       'Calvo',             'defensa',   'D'),
(429,'Jimmy',      'Bermudez',          'defensa',   'D'),
(430,'Lucas',      'Ahijado',           'defensa',   'Z'),
(431,'Nehuen',     'Paz',               'defensa',   'D'),
(432,'Carlos',     'Hernandez',         'defensa',   'D'),
(433,'Jordi',      'Sanchez',           'defensa',   'D'),
(434,'Santi',      'Cazorla',           'medio',     'A'),
(435,'Borja',      'Sanchez',           'medio',     'D'),
(436,'Manu',       'Garcia',            'medio',     'D'),
(437,'Alejandro',  'Repo',              'medio',     'D'),
(438,'Lucas',      'Benitez',           'medio',     'D'),
(439,'Sergio',     'Tejera',            'medio',     'D'),
(440,'Nacho',      'Vidal',             'defensa',   'D'),
(441,'Roberto',    'Suarez',            'delantero', 'D'),
(442,'Seydouba',   'Cisse',             'delantero', 'D'),
(443,'Marcos',     'Calderon',          'defensa',   'D'),
(444,'Bastian',    'Meier',             'medio',     'D'),
(445,'Arnau',      'Puig',              'medio',     'D'),
(446,'Jairo',      'Izquierdo',         'delantero', 'Z'),
(447,'Brayan',     'Riascos',           'delantero', 'D'),
(448,'Hugo',       'Rama',              'delantero', 'D'),
(449,'Adrian',     'Colunga',           'delantero', 'D'),
(450,'David',      'Costas',            'defensa',   'D'),

-- ============================================================
-- 19. ELCHE CF (entrenador: Eder Sarabia)
--     (ascendido de Segunda División)
-- ============================================================
(451,'Kiko',       'Casilla',           'portero',   'D'),
(452,'Pedro',      'Bigas',             'defensa',   'D'),
(453,'Tete',       'Morente',           'defensa',   'D'),
(454,'Juan',       'Cruz',              'defensa',   'Z'),
(455,'Patricio',   'Gabarrón',          'portero',   'D'),
(456,'Josema',     'Sanchez',           'defensa',   'D'),
(457,'Helibelton', 'Palacios',          'defensa',   'D'),
(458,'Lautaro',    'Blanco',            'defensa',   'Z'),
(459,'Fidel',      'Chaves',            'medio',     'D'),
(460,'Gus',        'Ledes',             'medio',     'D'),
(461,'Ezequiel',   'Ponce',             'delantero', 'D'),
(462,'Omar',       'Mascarell',         'medio',     'D'),
(463,'Andres',     'Garcia',            'medio',     'D'),
(464,'Alvaro',     'Sanchez',           'defensa',   'D'),
(465,'Sory',       'Kaba',              'delantero', 'D'),
(466,'Lucas',      'Perez',             'delantero', 'D'),
(467,'Raul',       'Guti',              'medio',     'D'),
(468,'Nico',       'Castro',            'medio',     'D'),
(469,'Christian',  'Rivera',            'medio',     'Z'),
(470,'Marc',       'Domenech',          'portero',   'D'),
(471,'Ivan',       'Marcone',           'medio',     'D'),
(472,'Ivan',       'Balliu',            'defensa',   'D'),
(473,'Samuel',     'Odobert',           'delantero', 'D'),
(474,'Gonzalo',    'Villar',            'medio',     'D'),
(475,'Claudio',    'Medina',            'defensa',   'D'),

-- ============================================================
-- 20. LEVANTE UD (entrenador: Luís Castro)
--     (ascendido de Segunda División)
-- ============================================================
(476,'Andriy',     'Lunin',             'portero',   'D'),
(477,'Pablo',      'Martinez',          'portero',   'D'),
(478,'Pepelu',     'Martinez',          'portero',   'D'),
(479,'Jose',       'Campana',           'medio',     'D'),
(480,'Carlos',     'Clerc',             'defensa',   'Z'),
(481,'Dani',       'Gomez',             'delantero', 'D'),
(482,'Gonzalo',    'Melero',            'medio',     'D'),
(483,'Jose',       'Luis Morales',      'delantero', 'Z'),
(484,'Son',        'Heung-Min',         'delantero', 'D'),
(485,'Enis',       'Bardhi',            'medio',     'D'),
(486,'Miquel',     'Crespi',            'defensa',   'D'),
(487,'Marc',       'Pubill',            'defensa',   'D'),
(488,'Rober',      'Pier',              'defensa',   'D'),
(489,'Sergio',     'Postigo',           'defensa',   'D'),
(490,'Nemanja',    'Radoja',            'medio',     'D'),
(491,'Roger',      'Marti',             'delantero', 'Z'),
(492,'Toño',       'Garcia',            'portero',   'D'),
(493,'Coke',       'Andujar',           'defensa',   'D'),
(494,'Iban',       'Salvador',          'medio',     'D'),
(495,'Marc',       'Relats',            'delantero', 'D'),
(496,'Mickael',    'Malsa',             'medio',     'D'),
(497,'Nikola',     'Vukcevic',          'medio',     'D'),
(498,'Ruben',      'Vezo',              'defensa',   'D'),
(499,'Marc',       'Pubill',            'defensa',   'D'),
(500,'Armando',    'Sadiku',            'delantero', 'D');
